name: CheckPaths

on: 
  push:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  CheckPaths:
    runs-on: windows-latest
    name: Check Paths
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: check paths
        shell: pwsh
        run: |
          .\actionFiles\checkPaths.ps1
