name: MakePdf

on:
  push:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  markdown:
    runs-on: windows-latest
    name: Generate Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate md Doc
        shell: pwsh
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          mkdir -p ${{ github.workspace }}/artifact/media/
          .\generateMarkdown.ps1 > ${{ github.workspace }}/artifact/doc.md
          mv .\bin\media\* ${{ github.workspace }}/artifact/media
      - uses: actions/upload-artifact@v3
        with:
          name: mdFile
          path: ${{ github.workspace }}/artifact/
  pdf:
    runs-on: ubuntu-latest
    name: Publish PDF
    needs: markdown
    steps:
      - name: create Folder
        run: |
          mkdir ${{ github.workspace }}/bin
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/bin/
          name: mdFile
      - name: Create PDF
        # You may pin to the exact commit or the version.
        # uses: mkrakowitzer/actions-makepdfs@07f1b3912a5dbcd72fe0feed3a3047a17c976d5e
        uses: mkrakowitzer/actions-makepdfs@v1.3
        with:
          # Location of markdown files in github repository
          markdown_dir: ${{ github.workspace }}/bin/doc.md # default is doc
          # Location to output PDF files to
          output_dir: ${{ github.workspace }}/bin/doc.pdf # default is tmp
      - name: Upload Document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'document.pdf'
          path: ${{ github.workspace }}/bin/doc.pdf
