name: MakePdf

on:
  push:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  markdown:
    runs-on: windows-latest
    name: Generate Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate md Doc
        shell: pwsh
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          mkdir -p ${{ github.workspace }}/artifact/media/
          .\generateMarkdown.ps1 > ${{ github.workspace }}/artifact/world.md
          mv .\bin\media\* ${{ github.workspace }}/artifact/bin/media
      - uses: actions/upload-artifact@v3
        with:
          name: mdFile
          path: ${{ github.workspace }}/artifact/
